#!/bin/sh

bspc config border_width          2
bspc config window_gap            8

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc monitor DVI-I-1 -d alpha beta gamma delta
bspc monitor DVI-D-0 -d epsilon lambda sigma omega

bspc config focused_border_color "#2E5780"

xmodmap ~/.xmodmap &
xset s off &
nitrogen --restore &
compton &
wmname LG3D &
~/bin/panel &
