#! /bin/sh

bspc monitor DVI-I-1 -d web code term misc
bspc monitor DVI-D-0 -d irc skype media other

bspc config border_width          2
bspc config window_gap            8
bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true


xmodmap ~/.xmodmap &
nitrogen --restore &
g15-desktop-service &
~/.config/bspwm/panel &
stalonetray &
wmname LG3D &
