#! /bin/sh
#
# Example panel for LemonBoy's bar

while read -r line ; do
	case $line in
		S*)
			# clock output
			sys_infos="\\br\\fr${line#?}"
			;;
		T*)
			# xtitle output
			title="\\br\\f0${line#?}"
			;;
		W*)
			# bspwm internal state
			wm_infos=""
			IFS=':'
			set -- ${line#?}
			while [ $# -gt 0 ] ; do
				item=$1
				name=${item#?}
				case $item in
					O*)
						# focused occupied desktop
						wm_infos="$wm_infos \\u1\\br\\f2 ${name} \\ur"
						;;
					F*)
						# focused free desktop
						wm_infos="$wm_infos \\u1\\br\\f2 ${name} \\ur"
						;;
					U*)
						# focused urgent desktop
						wm_infos="$wm_infos \\u1\\br\\f2 ${name} \\ur"
						;;
					o*)
						# occupied desktop
						wm_infos="$wm_infos \\br\\f0 ${name} "
						;;
					f*)
						# free desktop
						wm_infos="$wm_infos \\br\\f0 ${name} "
						;;
					u*)
						# urgent desktop
						wm_infos="$wm_infos \\u9\\br\\f0 ${name} \\ur"
						;;
					L*)
						# layout
						layout=$(printf "%s" "${name}" | sed 's/\(.\).*/\U\1/')
						wm_infos="$wm_infos    \\br\\f0$layout"
						;;
				esac
				shift
			done
			;;
	esac
	printf "%s\n" "\\l $wm_infos    |    $title \\r $sys_infos  "
done
