#!/bin/bash

if [ $(pgrep -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT


[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

. panel_colors

bspc config top_padding $PANEL_HEIGHT

bspc control --subscribe > "$PANEL_FIFO" &
conky -c "$HOME/bin/conky-bar" > "$PANEL_FIFO" &
python "$HOME/bin/unread.py" -m -r > "$PANEL_FIFO" &
sleep 1 && trayer --edge top --align right --transparent true --alpha 0 --tint 0x111111 --widthtype pixel --width 200 --height 20 &

cat "$PANEL_FIFO" \
    | panel_bar \
    | lemonbar \
        -f "Roboto-10,Koruri-10,sm4tik" \
        -F "$COLOR_FOREGROUND" \
        -B "$COLOR_BACKGROUND" \
        -g 3840x20 \
        -u 2 \
        -o -2 &


wait
